analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3447793,"name"\:"Sample - HR Web App \#3447793","teamId"\:3423600,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3479537,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3423600,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
